//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalNotes.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public Nullable<int> NotarialActionId { get; set; }
        public Nullable<int> NotarialActionTypeId { get; set; }
        public Nullable<int> NotarialActionObjectId { get; set; }
        public int ClientId { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int RecordNumber { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual NotarialAction NotarialAction { get; set; }
        public virtual NotarialActionsObject NotarialActionsObject { get; set; }
        public virtual NotarialActionsType NotarialActionsType { get; set; }
    }
}
