//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalNotes.DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LegalNotesEntities : DbContext
    {
        public LegalNotesEntities()
            : base("name=LegalNotesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NotarialAction> NotarialActions { get; set; }
        public virtual DbSet<NotarialActionsObject> NotarialActionsObjects { get; set; }
        public virtual DbSet<NotarialActionsType> NotarialActionsTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    }
}
