//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegalNotes.DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotarialActionsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotarialActionsType()
        {
            this.Documents = new HashSet<Document>();
            this.NotarialActionsObjects = new HashSet<NotarialActionsObject>();
        }
    
        public int NotarialActionTypeId { get; set; }
        public int NotarialActionId { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual NotarialAction NotarialAction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotarialActionsObject> NotarialActionsObjects { get; set; }
    }
}
